name: Setup Buildkite Test Splitter
description: Install Buildkite Test Splitter for use in Buildkite builds
author: https://github.com/sj26
requirements:
  - curl
  - jq
  - bash
configuration:
  properties:
    version:
      type: string
